# Exercise Lecture 2

**Q1.** Write a NumPy program to convert a list [1,2,3,4,5,6,7,8] into a one-dimensional NumPy array.

**Q2.** Reshape the above numpy array into shape of (2,4). Please provide two ways for doing this.


**Q3.** Change the data type of the above array to float.

**Q4**. Write a NumPy program to create a 1-D array with even values from 0 to 30.

**Q5**. Write a NumPy program to create a 1-D array of 20 evenly spaced elements between 0 and 1

**Q6.** Write a NumPy program to create a (4,4) array with 5 on the border and 0 inside.

**Q7**. Write a NumPy program to create a (4,4) array as follows:


```
[[1 2 0 0]

[3 1 2 0]

[0 3 1 2]

[0 0 3 1]]
```








**Q8**. Write a NumPy program to create an array of 50 in the shape (3,3)

**Q9**. Write a NumPy program to create a contiguous flattened array.
Original array:



```
[[1 2 3]

[9 10 11]]
```



First create the above array using np.array then convert it to 1D array.

**Q10**. Write a NumPy program to test whether specified values are present in an array.
For example you create an array [1 2 3 4 5]. and you test whether 20 is present in your array.

In [ ]:
import numpy as np
# the following code will generate (4,4) np array
a = np.arange(16).reshape(4,4)



**Q11.** write code to get element at position: row 1, column 2


**Q12.** write code to get first two rows


**Q13.** write code to get last two columns


**Q14.** What you think about the output of the following code

`print(a[[0, 1, 3], [0, 1, 2]])`

In [1]:
import numpy as np
# the following code will generate (4,4) np array
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**Q15.** write code to get [2,5,10,13,15]

**Q16** write code to change [2,5,10,13,15] with [10,20,30,40,50]

**Q17.** write code to get numbers greater than 10

**Q18** write code to get dot product of two arrays

**Q19.** Write a program which will plot the following data
$(1,2),(2,4),(3,9),(4,1)$

**Q20.** Change the marker, color and line style of the above plot

**Q21.** Plot the graph of the following polynomial function on the interval $(-2,2)$: $$f(x)=x^3+x^2+1$$

**Q22.** Make xlabel,ylabel,title and legend for above graph

**Q23.** Plot the graph(bar plot) for the following data:


**Day:** Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday

**Temperature:** 38,39,39,36,38,38,38





